"""Generates the fisherman sprite sheets from readable pixel maps.

Each appearance variant is baked into one 144x72 sheet laid out as a
9x3 grid of 16x24 frames:

    columns -> 0 = stand, 1 = walk A, 2 = walk B,
               3 = fish idle A, 4 = fish idle B, 5 = fish strike,
               6 = consume low, 7 = consume high, 8 = sit
    rows    -> 0 = facing down, 1 = facing right, 2 = facing up

Poses only exist for the direction they are actually used in: fishing is
always played facing right (fisherman.gd forces that on entering the
state, the water is east) and the need poses always face down. Every
other cell repeats that direction's stand frame, so an unexpected facing
degrades to standing rather than to a blank frame.

Sprite2D reads them directly via hframes/vframes/frame_coords, so the
game never slices or recolors anything at runtime.

Run from the repo root:

    python tools/generate_fisherman_sprites.py

Add --preview to also write a scaled-up contact sheet next to the
output for eyeballing the result.
"""

import argparse
import os

from PIL import Image

FRAME_W, FRAME_H = 16, 24
COLS, ROWS = 9, 3
OUT_DIR = os.path.join("assets", "sprites", "fisherman")

# --- Pixel maps -------------------------------------------------------
#
# Only body colors live in the maps; the dark outline is grown
# automatically from the silhouette afterwards, which keeps the maps
# readable and the outline consistent across every frame.
#
#   H hair   S skin   E eye    M mouth   B beard
#   T shirt  V overalls        K boots   A hat   a hat brim
#   R rod    P held item (food/drink)

DOWN_STAND = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HSSSSSSH....
....HSESSESH....
....HSSSSSSH....
....HSSMMSSH....
.....SSSSSS.....
......SSSS......
....TTTTTTTT....
...STTTTTTTTS...
...STVVVVVVTS...
...STVVVVVVTS...
...STVVVVVVTS...
....VVVVVVVV....
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....VVV..VVV....
....KKK..KKK....
....KKK..KKK....
................
"""

DOWN_WALK_A = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HSSSSSSH....
....HSESSESH....
....HSSSSSSH....
....HSSMMSSH....
.....SSSSSS.....
......SSSS......
...STTTTTTTTS...
...STTTTTTTTS...
...STVVVVVVTS...
...STVVVVVVTS...
....TVVVVVVT....
....VVVVVVVV....
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....KKK..VVV....
....KKK..KKK....
.........KKK....
................
"""

DOWN_WALK_B = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HSSSSSSH....
....HSESSESH....
....HSSSSSSH....
....HSSMMSSH....
.....SSSSSS.....
......SSSS......
....TTTTTTTT....
....TTTTTTTT....
...STVVVVVVTS...
...STVVVVVVTS...
...STVVVVVVTS...
...SVVVVVVVVS...
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....VVV..KKK....
....KKK..KKK....
....KKK.........
................
"""

# The side head is deliberately lopsided — hair wraps the back of the
# skull down to the nape, the eye sits forward of center, and the brow/
# nose break the front edge. A symmetric profile reads as a front-facing
# head sliding sideways instead of a character walking.
RIGHT_STAND = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHSSS....
....HHHSSSSS....
....HHHSSESSS...
....HHHSSSSSS...
....HHHSSSMM....
....HHSSSSS.....
....HHSSS.......
.....TTTTTT.....
....STTTTTTS....
....STVVVVTS....
....STVVVVTS....
....STVVVVTS....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....KKKKKK.....
.....KKKKKKK....
................
"""

# Walk A and B are the two contact poses. From the side both read as
# "legs apart", so the trailing leg is drawn in the shaded overalls/boot
# colors and they swap between frames — that's what makes the stride
# alternate instead of looking like a single repeated pose.
RIGHT_WALK_A = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHSSS....
....HHHSSSSS....
....HHHSSESSS...
....HHHSSSSSS...
....HHHSSSMM....
....HHSSSSS.....
....HHSSS.......
.....TTTTTTS....
....STTTTTTS....
....STVVVVTS....
....STVVVVT.....
....STVVVVT.....
.....VVVVVV.....
.....VVVVVV.....
....vvvv.VVV....
...vvvv..VVV....
...vvv....VVV...
..kkkk....KKKK..
..kkkk....KKKK..
................
"""

RIGHT_WALK_B = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHSSS....
....HHHSSSSS....
....HHHSSESSS...
....HHHSSSSSS...
....HHHSSSMM....
....HHSSSSS.....
....HHSSS.......
....STTTTTT.....
....STTTTTTS....
....STVVVVTS....
.....TVVVVTS....
.....TVVVVTS....
.....VVVVVV.....
.....VVVVVV.....
....VVVV.vvv....
...VVVV..vvv....
...VVV....vvv...
..KKKK....kkkk..
..KKKK....kkkk..
................
"""

UP_STAND = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
.....HHHHHH.....
......SSSS......
....TTTTTTTT....
...STTTTTTTTS...
...STVTTTTVTS...
...STVTTTTVTS...
...STVTTTTVTS...
....VVVVVVVV....
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....VVV..VVV....
....KKK..KKK....
....KKK..KKK....
................
"""

UP_WALK_A = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
.....HHHHHH.....
......SSSS......
...STTTTTTTTS...
...STTTTTTTTS...
...STVTTTTVTS...
...STVTTTTVTS...
....TVTTTTVT....
....VVVVVVVV....
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....KKK..VVV....
....KKK..KKK....
.........KKK....
................
"""

UP_WALK_B = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
....HHHHHHHH....
.....HHHHHH.....
......SSSS......
....TTTTTTTT....
....TTTTTTTT....
...STVTTTTVTS...
...STVTTTTVTS...
...STVTTTTVTS...
...SVVVVVVVVS...
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....VVV..KKK....
....KKK..KKK....
....KKK.........
................
"""

# Row-major, matching the sheet layout the game expects.
# --- Action poses -----------------------------------------------------
#
# Fishing: the rod runs up-right out of the leading hand. A and B differ
# by one pixel of rod angle, which is enough to read as a slow bob at
# 1-2 fps; the strike raises the rod steeply.
#
# The rod used to be a draw_line() call in fisherman.gd::_draw() -- an
# anti-aliased diagonal sitting off the pixel grid. Baking it in fixes
# that and animates it at the same time. The line stays drawn (as
# whole-pixel rects) because its length has to reach the water.
#
# Rod tips, which fisherman.gd hangs the line from, in frame pixels:
#   fish A -> (15, 10)   fish B -> (15, 11)   strike -> no line

RIGHT_FISH_A = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHSSS....
....HHHSSSSS....
....HHHSSESSS...
....HHHSSSSSS...
....HHHSSSMM....
....HHSSSSS.....
....HHSSS......R
.....TTTTTT...R.
....STTTTTTS.R..
....STVVVVTSR...
....STVVVVTS....
....STVVVVTS....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....KKKKKK.....
.....KKKKKKK....
................
"""

RIGHT_FISH_B = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHSSS....
....HHHSSSSS....
....HHHSSESSS...
....HHHSSSSSS...
....HHHSSSMM....
....HHSSSSS.....
....HHSSS.......
.....TTTTTT....R
....STTTTTTS..R.
....STVVVVTS.R..
....STVVVVTSR...
....STVVVVTS....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....KKKKKK.....
.....KKKKKKK....
................
"""

RIGHT_FISH_PULL = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHSSS....
....HHHSSSSS....
....HHHSSESSS...
....HHHSSSSSS..R
....HHHSSSMM...R
....HHSSSSS...R.
....HHSSS.....R.
.....TTTTTT..R..
....STTTTTTS.R..
....STVVVVTSR...
....STVVVVTS....
....STVVVVTS....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....VVVVVV.....
.....KKKKKK.....
.....KKKKKKK....
................
"""

# Eating and drinking share one pose pair. At 16x24 the held item is a
# couple of pixels, so a skewer and a bottle would be indistinguishable
# anyway -- which station the fisherman stands at is what tells them apart.
#
# The item sits beside the hand at x>=12 rather than centred on the face:
# BEARD_DOWN paints over rows 8-9 from x4 to x11, so a centred item
# silently disappeared on every bearded variant.

DOWN_CONSUME_LOW = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HSSSSSSH....
....HSESSESH....
....HSSSSSSH....
....HSSMMSSH....
.....SSSSSS.....
......SSSS......
....TTTTTTTT....
...STTTTTTTTS...
...STVVVVVVTSP..
...STVVVVVVTS...
...STVVVVVVTS...
....VVVVVVVV....
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....VVV..VVV....
....KKK..KKK....
....KKK..KKK....
................
"""

# Arm raised: the forearm climbs the x=12 column so the item reads as
# being lifted rather than teleporting up the frame.
DOWN_CONSUME_HIGH = """
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HSSSSSSH....
....HSESSESH....
....HSSSSSSH....
....HSSMMSSHP...
.....SSSSSS.S...
......SSSS..S...
....TTTTTTTTS...
...STTTTTTTTS...
...STVVVVVVTS...
...STVVVVVVTS...
...STVVVVVVT....
....VVVVVVVV....
....VVVVVVVV....
....VVV..VVV....
....VVV..VVV....
....VVV..VVV....
....KKK..KKK....
....KKK..KKK....
................
"""

# Seated: the whole figure drops a few rows and the legs read as thighs
# forward rather than standing columns.
DOWN_SIT = """
................
................
................
................
................
.....HHHHHH.....
....HHHHHHHH....
....HHHHHHHH....
....HSSSSSSH....
....HSESSESH....
....HSSSSSSH....
....HSSMMSSH....
.....SSSSSS.....
......SSSS......
....TTTTTTTT....
...STTTTTTTTS...
...STVVVVVVTS...
...STVVVVVVTS...
....VVVVVVVV....
....VVVVVVVV....
...KKKKKKKKKK...
...KKK....KKK...
................
................
"""

FRAMES = [
    [DOWN_STAND, DOWN_WALK_A, DOWN_WALK_B,
     DOWN_STAND, DOWN_STAND, DOWN_STAND,
     DOWN_CONSUME_LOW, DOWN_CONSUME_HIGH, DOWN_SIT],
    [RIGHT_STAND, RIGHT_WALK_A, RIGHT_WALK_B,
     RIGHT_FISH_A, RIGHT_FISH_B, RIGHT_FISH_PULL,
     RIGHT_STAND, RIGHT_STAND, RIGHT_STAND],
    [UP_STAND, UP_WALK_A, UP_WALK_B,
     UP_STAND, UP_STAND, UP_STAND,
     UP_STAND, UP_STAND, UP_STAND],
]

# --- Overlays ---------------------------------------------------------
#
# Drawn on top of a finished frame, so a hat brim can eat into the hair
# without every base map needing a hatted duplicate.

HAT_DOWN = """
................
.....AAAAAA.....
....AAAAAAAA....
....AAAAAAAA....
...aaaaaaaaaa...
................
"""

HAT_RIGHT = """
................
.....AAAAAA.....
....AAAAAAAA....
....AAAAAAAA....
....aaaaaaaaa...
................
"""

HAT_UP = """
................
.....AAAAAA.....
....AAAAAAAA....
....AAAAAAAA....
....aaaaaaaa....
................
"""

HATS = [HAT_DOWN, HAT_RIGHT, HAT_UP]

# Beards are a sparse list of (row, map) so they only touch the jaw.
BEARD_DOWN = [
    (8, "....BBBBBBBB...."),
    (9, ".....BBBBBB....."),
]
BEARD_RIGHT = [
    (8, "....BBBBBBBBB..."),
    (9, "....BBBBBBBBB..."),
]
BEARDS = {0: BEARD_DOWN, 1: BEARD_RIGHT}

# --- Palettes ---------------------------------------------------------
#
# v0 is the reference look: warm brown hair, red shirt, blue overalls.

SKIN = {
    "light": (240, 200, 168),
    "tan": (214, 166, 124),
    "brown": (170, 120, 84),
    "dark": (122, 82, 56),
}
HAIR = {
    "brown": (122, 78, 44),
    "black": (46, 38, 40),
    "blond": (222, 182, 96),
    "ginger": (188, 96, 44),
    "grey": (176, 176, 180),
}

PALETTES = [
    # skin,    hair,     shirt,           overalls,       boots,          hat,             beard
    ("light", "brown", (196, 68, 60), (58, 88, 142), (76, 56, 44), None, False),
    ("tan", "black", (66, 128, 108), (72, 66, 92), (58, 44, 38), (206, 176, 96), True),
    ("light", "blond", (222, 176, 72), (86, 74, 62), (72, 52, 40), None, False),
    ("brown", "black", (72, 104, 168), (60, 82, 70), (54, 44, 40), (168, 74, 66), False),
    ("light", "ginger", (168, 88, 152), (58, 88, 142), (76, 56, 44), None, True),
    ("dark", "black", (208, 112, 56), (52, 66, 96), (48, 40, 36), (96, 126, 92), False),
    ("tan", "brown", (92, 156, 168), (86, 62, 54), (62, 48, 40), None, True),
    ("light", "grey", (110, 122, 140), (74, 84, 106), (58, 50, 46), (140, 148, 160), True),
    ("brown", "brown", (140, 176, 84), (64, 60, 80), (52, 44, 40), None, False),
    ("tan", "blond", (196, 68, 60), (96, 82, 60), (70, 54, 42), (78, 108, 152), False),
]


def shade(color, factor):
    return tuple(max(0, min(255, int(c * factor))) for c in color)


def palette_for(index):
    skin_key, hair_key, shirt, overalls, boots, hat, beard = PALETTES[index]
    skin = SKIN[skin_key]
    hair = HAIR[hair_key]
    colors = {
        "H": hair,
        "S": skin,
        "E": (48, 38, 34),
        "M": shade(skin, 0.72),
        "B": shade(hair, 1.05),
        "T": shirt,
        "V": overalls,
        "v": shade(overalls, 0.72),
        "K": boots,
        "k": shade(boots, 0.72),
        # Props are shared across variants: a rod is a rod whoever holds it.
        # The line is not baked in -- see fisherman.gd::_draw(). The outline
        # pass grows around a 1px line and turns it into a 3px blade, and
        # its length has to reach the water anyway, so it is drawn instead.
        "R": (120, 82, 50),
        "P": (228, 198, 138),
    }
    if hat is not None:
        colors["A"] = hat
        colors["a"] = shade(hat, 0.78)
    return colors, hat is not None, beard


def parse_map(text):
    """Turns a map literal into a list of exactly FRAME_H rows."""
    rows = [line for line in text.strip("\n").split("\n")]
    if len(rows) != FRAME_H:
        raise ValueError("map has %d rows, expected %d" % (len(rows), FRAME_H))
    for row in rows:
        if len(row) != FRAME_W:
            raise ValueError("row %r is %d wide, expected %d" % (row, len(row), FRAME_W))
    return rows


def draw_frame(rows, colors, has_hat, has_beard, direction):
    px = {}
    for y, row in enumerate(rows):
        for x, char in enumerate(row):
            if char != ".":
                px[(x, y)] = colors[char]

    if has_beard and direction in BEARDS:
        for y, row in BEARDS[direction]:
            for x, char in enumerate(row):
                if char != "." and (x, y) in px:
                    px[(x, y)] = colors["B"]

    if has_hat:
        for y, row in enumerate(parse_overlay(HATS[direction])):
            for x, char in enumerate(row):
                if char != ".":
                    px[(x, y)] = colors[char]

    _apply_edge_shading(px)
    _apply_outline(px)

    image = Image.new("RGBA", (FRAME_W, FRAME_H), (0, 0, 0, 0))
    for (x, y), color in px.items():
        image.putpixel((x, y), color + (255,))
    return image


def parse_overlay(text):
    return [line for line in text.strip("\n").split("\n")]


def _apply_edge_shading(px):
    """Darkens the bottom edge of each body mass for a bit of volume.

    Deliberately the bottom and not a side: the side-facing frames get
    mirrored at runtime for the opposite direction, and side shading
    would flip the implied light source along with them.
    """
    shaded = {}
    for (x, y), color in px.items():
        if (x, y + 1) not in px:
            shaded[(x, y)] = shade(color, 0.84)
    px.update(shaded)


def _apply_outline(px):
    """Grows a 1px dark outline out of the silhouette.

    The outline color is derived from the pixel it touches rather than a
    flat black, so hair, cloth and skin each keep their own hue at the
    edges instead of the whole sprite reading as a sticker.
    """
    outline = {}
    for (x, y) in list(px.keys()):
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if not (0 <= nx < FRAME_W and 0 <= ny < FRAME_H):
                continue
            if (nx, ny) in px:
                continue
            outline.setdefault((nx, ny), shade(px[(x, y)], 0.42))
    px.update(outline)


def build_sheet(index):
    colors, has_hat, has_beard = palette_for(index)
    sheet = Image.new("RGBA", (FRAME_W * COLS, FRAME_H * ROWS), (0, 0, 0, 0))
    for row, frames in enumerate(FRAMES):
        for col, frame_map in enumerate(frames):
            frame = draw_frame(parse_map(frame_map), colors, has_hat, has_beard, row)
            sheet.paste(frame, (col * FRAME_W, row * FRAME_H))
    return sheet


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", action="store_true", help="also write a scaled contact sheet")
    args = parser.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    sheets = []
    for index in range(len(PALETTES)):
        sheet = build_sheet(index)
        path = os.path.join(OUT_DIR, "v%d.png" % index)
        sheet.save(path)
        sheets.append(sheet)
        print("wrote %s" % path)

    if args.preview:
        scale = 4
        gap = 8
        w = (sheets[0].width * scale + gap) * len(sheets) + gap
        h = sheets[0].height * scale + gap * 2
        contact = Image.new("RGBA", (w, h), (28, 34, 42, 255))
        for i, sheet in enumerate(sheets):
            big = sheet.resize((sheet.width * scale, sheet.height * scale), Image.NEAREST)
            contact.paste(big, (gap + i * (big.width + gap), gap), big)
        contact.save("sprite_preview.png")
        print("wrote sprite_preview.png")


if __name__ == "__main__":
    main()
